# list item format: (<layer module name>, <convenient reference name>)
unet_layers = [
    # 'model',
    # 'model.0.conv',
    # 'model.0.conv.unit0',
    # 'model.0.conv.unit0.conv',
    # 'model.0.conv.unit0.norm',
    # 'model.0.conv.unit0.act',
    # 'model.0.conv.unit1',
    # 'model.0.conv.unit1.conv',
    # 'model.0.conv.unit1.norm',
    # 'model.0.conv.unit1.act',
    #   'model.0.residual',
    ('model.0', 'l1 high res'), # high res for concat 0
    ('model.1.submodule', 'l1 low res'), # low res for concat 0
    ('model.1', 'l1 [high,low]'), # SkipConnection
    ('model.2', 'l1 final'),
    # 'model.1.submodule.0.conv',
    # 'model.1.submodule.0.conv.unit0',
    # 'model.1.submodule.0.conv.unit0.conv',
    # 'model.1.submodule.0.conv.unit0.norm',
    # 'model.1.submodule.0.conv.unit0.act',
    # 'model.1.submodule.0.conv.unit1',
    # 'model.1.submodule.0.conv.unit1.conv',
    # 'model.1.submodule.0.conv.unit1.norm',
    # 'model.1.submodule.0.conv.unit1.act',
    #   'model.1.submodule.0.residual',
    ('model.1.submodule.0', 'l2 high res'), # high res for concat 1
    ('model.1.submodule.1.submodule', 'l2 low res'), # low res for concat 1
    ('model.1.submodule.1', 'l2 [high,low]'),
    ('model.1.submodule.2', 'l2 final'),
    # 'model.1.submodule.1.submodule.0.conv',
    # 'model.1.submodule.1.submodule.0.conv.unit0',
    # 'model.1.submodule.1.submodule.0.conv.unit0.conv',
    # 'model.1.submodule.1.submodule.0.conv.unit0.norm',
    # 'model.1.submodule.1.submodule.0.conv.unit0.act',
    # 'model.1.submodule.1.submodule.0.conv.unit1',
    # 'model.1.submodule.1.submodule.0.conv.unit1.conv',
    # 'model.1.submodule.1.submodule.0.conv.unit1.norm',
    # 'model.1.submodule.1.submodule.0.conv.unit1.act',
    #   'model.1.submodule.1.submodule.0.residual',
    ('model.1.submodule.1.submodule.0', 'l3 high res'), # high res for concat 2
    ('model.1.submodule.1.submodule.1.submodule', 'l3 low res'), # low res for concat 2
    ('model.1.submodule.1.submodule.1', 'l3 [high,low]'),
    ('model.1.submodule.1.submodule.2', 'l3 final'),
    # 'model.1.submodule.1.submodule.1.submodule.0.conv',
    # 'model.1.submodule.1.submodule.1.submodule.0.conv.unit0',
    # 'model.1.submodule.1.submodule.1.submodule.0.conv.unit0.conv',
    # 'model.1.submodule.1.submodule.1.submodule.0.conv.unit0.norm',
    # 'model.1.submodule.1.submodule.1.submodule.0.conv.unit0.act',
    # 'model.1.submodule.1.submodule.1.submodule.0.conv.unit1',
    # 'model.1.submodule.1.submodule.1.submodule.0.conv.unit1.conv',
    # 'model.1.submodule.1.submodule.1.submodule.0.conv.unit1.norm',
    # 'model.1.submodule.1.submodule.1.submodule.0.conv.unit1.act',
    # 'model.1.submodule.1.submodule.1.submodule.0.residual',
    ('model.1.submodule.1.submodule.1.submodule.0', 'l4 high res'), # high res for concat 3
    ('model.1.submodule.1.submodule.1.submodule.1.submodule', 'l4 low res'), # low res for concat 3
    ('model.1.submodule.1.submodule.1.submodule.1', 'l4 [high,low]'),
    ('model.1.submodule.1.submodule.1.submodule.2', 'l4 final'),
    # 'model.1.submodule.1.submodule.1.submodule.1.submodule.conv',
    # 'model.1.submodule.1.submodule.1.submodule.1.submodule.conv.unit0',
    # 'model.1.submodule.1.submodule.1.submodule.1.submodule.conv.unit0.conv',
    # 'model.1.submodule.1.submodule.1.submodule.1.submodule.conv.unit0.norm',
    # 'model.1.submodule.1.submodule.1.submodule.1.submodule.conv.unit0.act',
    # 'model.1.submodule.1.submodule.1.submodule.1.submodule.conv.unit1',
    # 'model.1.submodule.1.submodule.1.submodule.1.submodule.conv.unit1.conv',
    # 'model.1.submodule.1.submodule.1.submodule.1.submodule.conv.unit1.norm',
    # 'model.1.submodule.1.submodule.1.submodule.1.submodule.conv.unit1.act',
    # 'model.1.submodule.1.submodule.1.submodule.1.submodule.residual',
    # 'model.1.submodule.1.submodule.1.submodule.2.0',
    # 'model.1.submodule.1.submodule.1.submodule.2.0.conv',
    # 'model.1.submodule.1.submodule.1.submodule.2.0.norm',
    # 'model.1.submodule.1.submodule.1.submodule.2.0.act',
    # 'model.1.submodule.1.submodule.1.submodule.2.1',
    # 'model.1.submodule.1.submodule.1.submodule.2.1.conv',
    # 'model.1.submodule.1.submodule.1.submodule.2.1.conv.unit0',
    # 'model.1.submodule.1.submodule.1.submodule.2.1.conv.unit0.conv',
    # 'model.1.submodule.1.submodule.1.submodule.2.1.conv.unit0.norm',
    # 'model.1.submodule.1.submodule.1.submodule.2.1.conv.unit0.act',
    # 'model.1.submodule.1.submodule.1.submodule.2.1.residual',
    # 'model.1.submodule.1.submodule.2.0',
    # 'model.1.submodule.1.submodule.2.0.conv',
    # 'model.1.submodule.1.submodule.2.0.norm',
    # 'model.1.submodule.1.submodule.2.0.act',
    # 'model.1.submodule.1.submodule.2.1',
    # 'model.1.submodule.1.submodule.2.1.conv',
    # 'model.1.submodule.1.submodule.2.1.conv.unit0',
    # 'model.1.submodule.1.submodule.2.1.conv.unit0.conv',
    # 'model.1.submodule.1.submodule.2.1.conv.unit0.norm',
    # 'model.1.submodule.1.submodule.2.1.conv.unit0.act',
    # 'model.1.submodule.1.submodule.2.1.residual',
    # 'model.1.submodule.2.0',
    # 'model.1.submodule.2.0.conv',
    # 'model.1.submodule.2.0.norm',
    # 'model.1.submodule.2.0.act',
    # 'model.1.submodule.2.1',
    # 'model.1.submodule.2.1.conv',
    # 'model.1.submodule.2.1.conv.unit0',
    # 'model.1.submodule.2.1.conv.unit0.conv',
    # 'model.1.submodule.2.1.conv.unit0.norm',
    # 'model.1.submodule.2.1.conv.unit0.act',
    # 'model.1.submodule.2.1.residual',
    # 'model.2.0',
    # 'model.2.0.conv',
    # 'model.2.0.norm',
    # 'model.2.0.act',
    # 'model.2.1',
    # 'model.2.1.conv',
    # 'model.2.1.conv.unit0',
    # 'model.2.1.conv.unit0.conv',
    # 'model.2.1.residual',
]

att_unet_layers = [
    ('', 'Input'),
    ('Conv1', 'l1 high res'),
    ('Up_conv2', 'l1 final'),
    ('Conv2', 'l2 high res'),
    ('Up_conv3', 'l2 final'),
    ('Conv3', 'l3 high res'),
    ('Up_conv4', 'l3 final'),
    ('Conv4', 'l4 high res'),
    ('Up_conv5', 'l4 final'),
]

unet_2d_layers = [
    ('', 'Input'),
    ('dconv_down1', 'l1 high res'),
    ('dconv_up1', 'l1 final'),
    ('dconv_down2', 'l2 high res'),
    ('dconv_up2', 'l2 final'),
    ('dconv_down3', 'l3 high res'),
    ('dconv_up3', 'l3 final'),
    ('dconv_down4', 'l4 high res'),
    ('upsample', 'l4 final'),
]
